export const ROUTE_DATA = {
  FROM_ADD_LOTTERY_TO_TAGS: "ADD_LOTTERY_TO_TAGS",
  BACK_PIC_DETAILS_TO_ADD_LOTTERY: "BACK_PIC_DETAILS_TO_ADD_LOTTERY",
  FROM_ADD_LOTTERY_TO_PIC_DETAILS: "FROM_ADD_LOTTERY_TO_PIC_DETAILS",
  BACK_TAGS_TO_ADD_LOTTERY: "BACK_TAGS_TO_ADD_LOTTERY",
  FROM_ATTEND_LOTTERY_TO_SHARE_PIC: "FROM_ATTEND_LOTTERY_TO_SHARE_PIC",
  FROM_ATTEND_LOTTERY_TO_HOME: "FROM_ATTEND_LOTTERY_TO_HOME",
  FROM_HOME_TO_ATTEND_LOTTERY: "FROM_ATTEND_LOTTERY_TO_HOME"
};

export const ATTEND_LOTTERY_EVENT = "attend_lottery_event";
export const DEFAULT_SPONSOR = "好运码头";
export const ADDRESS = "收货地址";

export const PAGE_SIZE = 8;
